### ISSUE TITLE
Latest channels issue

### ISSUE THREAD

**Issue by nsmarcin** [ottnav/ottnav.github.io#1]
1. Open category
2. Open channel
3. Open different category
4. Open different channel
5. On remote click OK 
6. Pick latest channel from hud menu
7. On remote click UP
Now you're supposed to see channel list for category of that channel but instead you see channel list of Recent opened channels. 
This occures only in newer versions with three "latest channels" in hud menu.

**Comment by ottnav** [comment]
contact app developer via email from store, github issues are not accepted
