### ISSUE TITLE
Bug: launch OTT no direct to channel and no more startup when device power-on

### ISSUE THREAD

**Issue by hispanico957** [ottnav/ottnav.github.io#12]
Whit 2nd gen firesticks (2023) as there are 2 problems that didn't exist with the 1st gen Firesticks

1 - when launch OTT always appear this image (screen selection) and not the channels or last channel played, also if i select to play last channel on startup of app. This happened also with NVidia Shield PRO

![One (2) (1)](https://github.com/ottnav/ottnav.github.io/assets/15804373/b924dcc7-3ada-4acf-a584-27ee6e1e61e8)

2 - now the OTT app no longer starts automatically when the FireTV is started, as it happened with the still 4K Max but old FireTV. 

![two (2) (1)](https://github.com/ottnav/ottnav.github.io/assets/15804373/e8a3fbd3-a0ee-4fe0-93c7-1c3aed5a0f25)

Hispa

**Comment by ottnav** [comment]
send email to support with more details about the issue
