### ISSUE TITLE
The same logo appears on all channels

### ISSUE THREAD

**Issue by dikodahan** [ottnav/ottnav.github.io#4]
I am seeing the same logo appear on the top right corner of the screen of the screen, no matter which channel I switch to.
I do not see that on other IPTV players.

The actual channel logos, as you can see on the left side, are all accurate as they are received from the M3U file. But no matter which channel I switch to, the logo on the top right corner remains. The only potential correlation I could find (just a theory) is that this logo on the top right corner is the first channel listed on the EPG source. Again, I am not sure if there is a correlation, but thought it is worth mentioning it.

![062423151159](https://github.com/ottnav/ottnav.github.io/assets/38052895/fbb58920-3f91-40d4-aa2d-77b58b5ce829)
![062423151218](https://github.com/ottnav/ottnav.github.io/assets/38052895/3fa6982d-e6d2-428e-a66e-d561a0e990ec)
![062423151228](https://github.com/ottnav/ottnav.github.io/assets/38052895/400ff2ba-91eb-4e9d-9ab0-518d15e92103)

Any idea why this is happening??
just for context, this is using the latest premium version of 1.6.9.3

**Comment by ottnav** [comment]
report your issue with details via email scillarium.studio@gmail.com
