### ISSUE TITLE
BUG: "Difference From System Time" is broken 

### ISSUE THREAD

**Issue by frozen905** [ottnav/ottnav.github.io#9]
Hello

I have a provider who's EPG is off by three hours. 

Going to it's Provider Properties you scroll down to EPG Teleguide and choose the "Difference From System Time" option, and it appears to do nothing at all. It does not save your selection, and instantly resets or simply doesn't apply. 

I have set huge values like 12 hour differences and I believe it is simply a bug, and fully broken

The only way to fix the channels is edit them one by one, and adjust them individually, which will take days to complete

All other apps and even the most basic 10 year old MAG boxes have this feature, so it needs addressing

I am a fully paid user using latest.apk directly. 

Thank you

**Comment by ottnav** [comment]
send email to support with more details about the issue
